# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://riddlegirl.github.io/
title: 新住宅
email: wowdecoration@163.com
author: WOW
description: New Home
copyright: 'Copyright &copy; 2015 新住宅. All Rights Reserved.'
credits: '020-38343625 <br> wowdecoration@163.com <br> <a href="http://map.baidu.com/?newmap=1&ie=utf-8&s=s%26wd%3D%E7%9F%B3%E7%89%8C%E5%8D%97%E9%97%A8%E8%8B%91">广州市天河区瘦狗岭路583号</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

