# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://WOW-Decorate.github.io/NEWHOME
title: º“‘√
email: wowdecoration@163.com
author: JiaYue 
description: JiaYue
copyright: 'Copyright &copy; Your Awesome Site. All Rights Reserved.'
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

