# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://riddlegirl.github.io/
title: 新住宅
email: wowdecoration@163.com
author: WOW
description: New Home
copyright: 'Copyright &copy; 2015 新住宅. All Rights Reserved.'
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

